### ISSUE TITLE
Proposal: Archive this project

### ISSUE THREAD

**Issue by tetsuharuohzeki** [cats-oss/eslint-config-abema#598]
[After this announcement](https://github.com/cats-oss/eslint-config-abema/issues/247), the time has been passed.

I'm not sure about that how much "abema" core products still depends on this project,  but I think it's time to archive this project. Because:

1. Now, I don't have enough time to maintain this repository and I would not touch this project for the time being. 
1. I'm not a paid staff for this upstream product for a long time and I'm not a strong stakeholder of this project. I think it would not be a proper position to make a decision of this project.
1. I heared that "abema" products decrease the strong dependency for this project in 2019 in #247. After 2 years ago,  I'm not sure about that how much "abema" core products still depends on this project, but I guess there is no dependency for this.
1. There is no other active contributor/maintainer. This is a biggest reason which I propose this.

Therefore, for the aspect of branding, I think it's better that we should archive this inactive project. Archiving this repository does not mean that removals of all of codes. It continues to open-source codes. But it's nice to tell that this project is inactive obviously.

Of course, if some paid staffs retry to make this project active, then we can unarchive this. But it's not now.

----------------

@nodaguti @kubosho

How did you think about this?

answer deadline: 2021, Nov, 19th, 24:00 (UTC+9:00).
If there is no objection until this date, I'll archive this (Probably I have a permission to do it).

**Comment by tetsuharuohzeki** [comment]
> Now, I don't have enough time to maintain this repository and I would not touch this project for the time being.

Even if I come back to maintain this kind of rule set when I got a time, I would fork this project and change it for my purpose. It does not make sense to continue to maintain _this_ with _this project name_.

**Comment by nodaguti** [comment]
@tetsuharuohzeki 
Sorry for taking some time to make a reply with your suggestion.

I'm for the proposal; As you noted, no repositories in our product use this configuration at this moment and there is no plan to re-introduce it as well. You have been virtually the only active maintainer of this project, so it's a good reason to cease the project when you are no longer motivated to maintain it.

Thank you so much for your incrediable efforts into this project for such a long time! The contributions you have made were undoutedly awesome!

**Comment by nodaguti** [comment]
> It does not make sense to continue to maintain this with this project name.

I totally agree with this. Since this rule set is no longer used by any repositories within the AbemaTV organisation, the name "abema" is quite misleading.

**Comment by kubosho** [comment]
I agree with the proposal.

Currently in our project, we are configuring lint based on `eslint:recommended`. So we don't use `eslint-config-abema`.

Thanks for the long time maintenance!

**Comment by tetsuharuohzeki** [comment]
Thank you for your feedback! I will proceed this proposal.

> Thanks for the long time maintenance!

It’s a pleasure.
